function embname(frases) {
    return frases.sort(() => Math.random() - 0.5);
}
const frases = [
    "Você não está sozinho, eu estarei aqui para te ajudar sempre.",
    "A dor pode parecer eterna, mas um dia ela vai passar.",
    "Sei que é difícil agora, mas você vai superar isso.",
    "Você é mais forte do que imagina e logo verá isso.",
    "Nunca se esqueça do quão incrível e especial você é.",
    "Não tenha medo de chorar, suas emoções são totalmente válidas.",
    "Estarei ao seu lado, segurando sua mão sempre que precisar.",
    "Às vezes, só precisamos de um abraço para acalmar a alma.",
    "Você não precisa carregar esse peso sozinho, pode contar comigo.",
    "Nenhuma tempestade dura para sempre, um dia o sol volta a brilhar.",
    "O tempo pode curar feridas que hoje parecem impossíveis de fechar.",
    "Cada dia é uma nova chance para recomeçar e tentar de novo.",
    "Quando menos esperar, tudo isso será apenas uma lembrança distante.",
    "A dor pode ser forte agora, mas logo dará lugar à paz.",
    "Confie no futuro, ele guarda coisas boas esperando por você.",
    "Você é mais capaz do que imagina, acredite em seu potencial.",
    "Não perca a esperança, coisas incríveis podem acontecer a qualquer momento.",
    "A vida sempre encontra uma forma de nos surpreender positivamente.",
    "Seu sorriso ainda voltará a brilhar, mais forte do que antes.",
    "O que parece um fim agora pode ser um novo começo.",
    "Cada obstáculo vencido é uma prova do quanto você é forte.",
    "Sua história ainda está sendo escrita, e muitos capítulos virão.",
    "Grandes batalhas são dadas apenas para aqueles que podem vencê-las.",
    "Você já superou desafios antes e conseguirá superar esse também.",
    "Continue em frente, pois o seu futuro brilha à sua espera.",
    "A vida é um ciclo, momentos ruins sempre dão lugar aos bons.",
    "Não deixe a tristeza apagar a luz que existe em você.",
    "Você é um guerreiro e sua força inspira mais pessoas do que imagina.",
    "O mundo precisa de você e do seu brilho único e especial.",
    "A sua existência faz diferença, mesmo que às vezes pareça insignificante.",
    "Você pode não perceber, mas tem pessoas que realmente se importam.",
    "Eu estou aqui para você, em qualquer momento que precisar.",
    "Sua dor é compreendida e você nunca estará sozinho nessa caminhada.",
    "Sempre há alguém disposto a ouvir e te oferecer apoio sincero.",
    "Você não precisa enfrentar tudo sozinho, pode dividir sua carga.",
    "Há amor ao seu redor, mesmo que pareça difícil enxergar agora.",
    "Seu coração merece paz, carinho e compreensão, nunca se esqueça disso.",
    "Lembre-se de que sua vida é valiosa e importante para muitos.",
    "Você pode contar comigo sempre, não importa o que aconteça.",
    "Nos momentos difíceis, lembre-se de que alguém se importa com você.",
    "Eu sei que está doendo, mas você não precisa sofrer sozinho.",
    "Sua dor não é fraqueza, mas um sinal da sua humanidade.",
    "Você é amado, mesmo que agora não consiga perceber isso.",
    "O tempo pode não apagar tudo, mas pode suavizar a dor.",
    "Você merece sentir felicidade novamente, e isso acontecerá no momento certo.",
    "Se precisar de um ombro amigo, eu estarei aqui para você.",
    "Não há problema em precisar de ajuda para seguir em frente.",
    "A tristeza pode ser pesada, mas não precisa carregar sozinha.",
    "Você ainda encontrará motivos para sorrir, mesmo que pareça impossível.",
    "A vida pode ser difícil, mas sempre há um novo amanhecer.",
    "Você é valioso exatamente do jeito que é, sem precisar mudar.",
    "Sua existência já é suficiente para tornar este mundo um lugar melhor.",
    "Você tem qualidades incríveis, mesmo que às vezes esqueça disso.",
    "Não deixe a dor ofuscar o brilho que existe em você.",
    "Seu coração é forte, e sua essência é única e maravilhosa.",
    "O mundo precisa da sua luz, nunca duvide do seu valor.",
    "Não se compare com os outros, pois você é especial à sua maneira.",
    "Você é digno de amor, felicidade e tudo de melhor na vida.",
    "Seu valor não é definido por erros, mas pelo seu coração.",
    "Você tem algo especial dentro de si, e isso ninguém pode tirar.",
    "Cada experiência, mesmo dolorosa, traz um aprendizado valioso para nossa vida.",
    "Você está evoluindo todos os dias, mesmo que não perceba isso agora.",
    "Suas cicatrizes contam sua história, mas não definem quem você é.",
    "Grandes mudanças começam com pequenos passos, e cada avanço importa.",
    "O caminho pode ser difícil, mas a chegada valerá a pena.",
    "Você pode estar ferido agora, mas um dia sentirá paz novamente.",
    "A dor de hoje pode ser a força de amanhã, acredite nisso.",
    "A cada dificuldade superada, você se torna ainda mais resiliente e forte.",
    "Você pode cair quantas vezes for necessário, mas sempre levante-se novamente.",
    "Seu futuro tem muito a oferecer, nunca deixe de acreditar nisso.",
    "A saudade pode doer, mas as lembranças sempre manterão o amor vivo.",
    "Nenhuma despedida é para sempre, o amor permanece em nossas memórias.",
    "Sua dor é compreendida e respeitada, você não está sozinho.",
    "As pessoas que amamos nunca nos deixam completamente, vivem em nós.",
    "Permita-se sentir e processar essa perda, sem pressa para superar.",
    "Seu coração pode estar machucado agora, mas ele encontrará paz novamente.",
    "As lembranças felizes sempre serão um refúgio nos momentos de dor.",
    "A perda pode ser difícil, mas você não precisa enfrentá-la sozinho.",
    "Um dia a dor se transformará em saudade carregada de amor.",
    "Permita-se viver o luto, mas também abra espaço para a esperança.",
    "Nunca é tarde para recomeçar, sua história ainda tem muitos capítulos.",
    "O primeiro passo pode ser difícil, mas é necessário para avançar.",
    "Você não é seu passado, pode criar um futuro completamente novo.",
    "Mudanças fazem parte da vida, e você pode usá-las a seu favor.",
    "Cada recomeço traz novas possibilidades que podem surpreender positivamente.",
    "Liberte-se do que te prende e abrace as novas oportunidades.",
    "Você merece ser feliz, não tenha medo de buscar isso.",
    "Nunca subestime sua capacidade de dar a volta por cima.",
    "O mundo está cheio de possibilidades esperando por você descobrir.",
    "Seu futuro pode ser mais brilhante do que você imagina.",
    "Respire fundo, um passo de cada vez e tudo ficará bem.",
    "Sua paz interior vale mais do que qualquer coisa neste mundo.",
    "O agora é tudo o que temos, aproveite cada momento presente.",
    "Se permita descansar, sua mente e coração precisam de um tempo.",
    "Você merece momentos de calma, então desacelere e respire fundo.",
    "O silêncio e a tranquilidade também são formas de cura.",
    "Não se cobre tanto, a vida acontece no seu próprio tempo.",
    "Feche os olhos, inspire profundamente e solte toda a tensão.",
    "O amor-próprio começa quando aprendemos a nos tratar com gentileza.",
    "Cuide de si mesmo como cuidaria de alguém que ama.",
    "Você não está sozinho, eu estarei aqui para te ajudar sempre.",
    "A dor pode parecer eterna, mas um dia ela vai passar.",
    "Sei que é difícil agora, mas você vai superar isso.",
    "Você é mais forte do que imagina e logo verá isso.",
    "Nunca se esqueça do quão incrível e especial você é.",
    "Não tenha medo de chorar, suas emoções são totalmente válidas.",
    "Estarei ao seu lado, segurando sua mão sempre que precisar.",
    "Às vezes, só precisamos de um abraço para acalmar a alma.",
    "Você não precisa carregar esse peso sozinho, pode contar comigo.",
    "Nenhuma tempestade dura para sempre, um dia o sol volta a brilhar.",
    "O tempo pode curar feridas que hoje parecem impossíveis de fechar.",
    "Cada dia é uma nova chance para recomeçar e tentar de novo.",
    "Quando menos esperar, tudo isso será apenas uma lembrança distante.",
    "A dor pode ser forte agora, mas logo dará lugar à paz.",
    "Confie no futuro, ele guarda coisas boas esperando por você.",
    "Você é mais capaz do que imagina, acredite em seu potencial.",
    "Não perca a esperança, coisas incríveis podem acontecer a qualquer momento.",
    "A vida sempre encontra uma forma de nos surpreender positivamente.",
    "Seu sorriso ainda voltará a brilhar, mais forte do que antes.",
    "O que parece um fim agora pode ser um novo começo.",
    "Cada obstáculo vencido é uma prova do quanto você é forte.",
    "Sua história ainda está sendo escrita, e muitos capítulos virão.",
    "Grandes batalhas são dadas apenas para aqueles que podem vencê-las.",
    "Você já superou desafios antes e conseguirá superar esse também.",
    "Continue em frente, pois o seu futuro brilha à sua espera.",
    "A vida é um ciclo, momentos ruins sempre dão lugar aos bons.",
    "Não deixe a tristeza apagar a luz que existe em você.",
    "Você é um guerreiro e sua força inspira mais pessoas do que imagina.",
    "O mundo precisa de você e do seu brilho único e especial.",
    "A sua existência faz diferença, mesmo que às vezes pareça insignificante.",
    "Você pode não perceber, mas tem pessoas que realmente se importam.",
    "Eu estou aqui para você, em qualquer momento que precisar.",
    "Sua dor é compreendida e você nunca estará sozinho nessa caminhada.",
    "Sempre há alguém disposto a ouvir e te oferecer apoio sincero.",
    "Você não precisa enfrentar tudo sozinho, pode dividir sua carga.",
    "Há amor ao seu redor, mesmo que pareça difícil enxergar agora.",
    "Seu coração merece paz, carinho e compreensão, nunca se esqueça disso.",
    "Lembre-se de que sua vida é valiosa e importante para muitos.",
    "Você pode contar comigo sempre, não importa o que aconteça.",
    "Nos momentos difíceis, lembre-se de que alguém se importa com você.",
    "Eu sei que está doendo, mas você não precisa sofrer sozinho.",
    "Sua dor não é fraqueza, mas um sinal da sua humanidade.",
    "Você é amado, mesmo que agora não consiga perceber isso.",
    "O tempo pode não apagar tudo, mas pode suavizar a dor.",
    "Você merece sentir felicidade novamente, e isso acontecerá no momento certo.",
    "Se precisar de um ombro amigo, eu estarei aqui para você.",
    "Não há problema em precisar de ajuda para seguir em frente.",
    "A tristeza pode ser pesada, mas não precisa carregar sozinha.",
    "Você ainda encontrará motivos para sorrir, mesmo que pareça impossível.",
    "A vida pode ser difícil, mas sempre há um novo amanhecer.",
    "Você é valioso exatamente do jeito que é, sem precisar mudar.",
    "Sua existência já é suficiente para tornar este mundo um lugar melhor.",
    "Você tem qualidades incríveis, mesmo que às vezes esqueça disso.",
    "Não deixe a dor ofuscar o brilho que existe em você.",
    "Seu coração é forte, e sua essência é única e maravilhosa.",
    "O mundo precisa da sua luz, nunca duvide do seu valor.",
    "Não se compare com os outros, pois você é especial à sua maneira.",
    "Você é digno de amor, felicidade e tudo de melhor na vida.",
    "Seu valor não é definido por erros, mas pelo seu coração.",
    "Você tem algo especial dentro de si, e isso ninguém pode tirar.",
    "Cada experiência, mesmo dolorosa, traz um aprendizado valioso para nossa vida.",
    "Você está evoluindo todos os dias, mesmo que não perceba isso agora.",
    "Suas cicatrizes contam sua história, mas não definem quem você é.",
    "Grandes mudanças começam com pequenos passos, e cada avanço importa.",
    "O caminho pode ser difícil, mas a chegada valerá a pena.",
    "Você pode estar ferido agora, mas um dia sentirá paz novamente.",
    "A dor de hoje pode ser a força de amanhã, acredite nisso.",
    "A cada dificuldade superada, você se torna ainda mais resiliente e forte.",
    "Você pode cair quantas vezes for necessário, mas sempre levante-se novamente.",
    "Seu futuro tem muito a oferecer, nunca deixe de acreditar nisso.",
    "A saudade pode doer, mas as lembranças sempre manterão o amor vivo.",
    "Nenhuma despedida é para sempre, o amor permanece em nossas memórias.",
    "Sua dor é compreendida e respeitada, você não está sozinho.",
    "As pessoas que amamos nunca nos deixam completamente, vivem em nós.",
    "Permita-se sentir e processar essa perda, sem pressa para superar.",
    "Seu coração pode estar machucado agora, mas ele encontrará paz novamente.",
    "As lembranças felizes sempre serão um refúgio nos momentos de dor.",
    "A perda pode ser difícil, mas você não precisa enfrentá-la sozinho.",
    "Um dia a dor se transformará em saudade carregada de amor.",
    "Permita-se viver o luto, mas também abra espaço para a esperança.",
    "Nunca é tarde para recomeçar, sua história ainda tem muitos capítulos.",
    "O primeiro passo pode ser difícil, mas é necessário para avançar.",
    "Você não é seu passado, pode criar um futuro completamente novo.",
    "Mudanças fazem parte da vida, e você pode usá-las a seu favor.",
    "Cada recomeço traz novas possibilidades que podem surpreender positivamente.",
    "Liberte-se do que te prende e abrace as novas oportunidades.",
    "Você merece ser feliz, não tenha medo de buscar isso.",
    "Nunca subestime sua capacidade de dar a volta por cima.",
    "O mundo está cheio de possibilidades esperando por você descobrir.",
    "Seu futuro pode ser mais brilhante do que você imagina.",
    "Respire fundo, um passo de cada vez e tudo ficará bem.",
    "Sua paz interior vale mais do que qualquer coisa neste mundo.",
    "O agora é tudo o que temos, aproveite cada momento presente.",
    "Se permita descansar, sua mente e coração precisam de um tempo.",
    "Você merece momentos de calma, então desacelere e respire fundo.",
    "O silêncio e a tranquilidade também são formas de cura.",
    "Não se cobre tanto, a vida acontece no seu próprio tempo.",
    "Feche os olhos, inspire profundamente e solte toda a tensão.",
    "O amor-próprio começa quando aprendemos a nos tratar com gentileza.",
    "Cuide de si mesmo como cuidaria de alguém que ama.",
    "O que importa não é o destino, mas o caminho que percorremos.",
    "Cada ato de amor é um passo em direção à paz.",
    "A verdadeira força vem do coração e da capacidade de amar.",
    "O tempo não cura, mas ensina a lidar com a dor.",
    "Às vezes, a beleza está na simplicidade do momento.",
    "A vida é uma aventura e a verdadeira coragem está em viver cada dia.",
    "Não importa quão escuro o caminho seja, sempre há luz no fim.",
    "A verdadeira felicidade é saber que você fez o seu melhor.",
    "Cada amanhecer é uma nova chance para recomeçar.",
    "A vida é feita de escolhas, e o amor é sempre a melhor delas.",
    "O amor é a força que transcende todas as barreiras.",
    "Os sonhos são os guias da nossa alma, nos mostrando o que podemos alcançar.",
    "A beleza de um momento não está em sua perfeição, mas em sua sinceridade.",
    "A verdadeira paz é aquela que vem de dentro, não do que está ao nosso redor.",
    "Os melhores momentos são aqueles compartilhados com quem amamos.",
    "A gratidão transforma tudo o que tocamos.",
    "A vida é curta demais para não aproveitar cada oportunidade de ser feliz.",
    "O mais importante na vida é ser fiel a si mesmo.",
    "O amor é a única coisa que cresce quanto mais se dá.",
    "Quando você se permite ser quem é, o mundo começa a se ajustar a você.",
    "Cada cicatriz é uma lembrança de que você é mais forte do que pensa.",
    "A verdadeira sabedoria está em saber escutar o coração.",
    "Às vezes, a maior coragem é simplesmente seguir em frente.",
    "O verdadeiro luxo é a paz interior que conquistamos.",
    "A vida é como um livro: cada página traz uma nova história.",
    "Cada momento de dor é uma oportunidade para crescer e aprender.",
    "A felicidade não é um destino, mas uma forma de viver.",
    "A verdadeira liberdade está em ser capaz de se reinventar a cada dia.",
    "Os melhores sentimentos são os que vêm de um coração aberto.",
    "Nunca subestime o poder de um sorriso sincero.",
    "O tempo ensina que tudo o que realmente importa é o amor.",
    "O que você faz hoje molda o amanhã, então viva com intenção.",
    "Às vezes, é preciso se perder para encontrar o caminho de volta.",
    "O mundo é um reflexo daquilo que cultivamos dentro de nós.",
    "O verdadeiro sucesso é viver com propósito e gratidão.",
    "Cada dia é uma nova oportunidade para ser a melhor versão de si mesmo.",
    "A paz começa no coração de cada um de nós.",
    "O amor é a razão de tudo o que vale a pena na vida.",
    "A verdadeira beleza de uma pessoa está na luz que ela irradia.",
    "Você nunca está sozinho quando tem amor em seu coração.",
    "A verdadeira magia da vida está em como escolhemos viver cada momento.",
    "A alma é eterna, e sua luz nunca se apaga.",
    "O segredo para uma vida plena está na aceitação do que não podemos controlar.",
    "Cada dificuldade que enfrentamos é uma oportunidade para amadurecer.",
    "A felicidade é um estado de espírito, não um lugar a ser alcançado.",
    "O sorriso de uma criança tem o poder de iluminar qualquer dia.",
    "Cada dia é uma nova chance para ser melhor e fazer o bem.",
    "O amor é a chave que abre todas as portas da vida.",
    "A vida é uma obra de arte que você mesmo pode pintar.",
    "Não existe o momento perfeito para ser feliz, a felicidade é agora.",
    "Os sonhos são o combustível que nos mantém em movimento.",
    "A verdadeira paz está em aceitar o que não podemos mudar.",
    "O futuro pertence àqueles que acreditam na beleza dos seus sonhos.",
    "A vida é uma jornada, não uma corrida.",
    "O amor é a linguagem universal que todos entendem.",
    "A verdadeira sabedoria é aprender a viver com simplicidade.",
    "Cada pequeno gesto de bondade tem o poder de transformar o mundo.",
    "A vida é uma dança entre o ser e o tornar-se.",
    "O verdadeiro significado da vida está em dar e receber amor.",
    "Cada dia é uma nova oportunidade para construir algo significativo.",
    "Os verdadeiros amigos são como estrelas, você nem sempre os vê, mas sabe que estão lá.",
    "A vida é uma música, e você é o maestro da sua própria melodia.",
    "A paz começa dentro de cada um de nós, espalhe-a ao seu redor.",
    "A felicidade está em saber que você fez o seu melhor, independentemente do resultado.",
    "A verdadeira liberdade é ser fiel a si mesmo, sem se preocupar com as opiniões alheias.",
    "A vida é um presente, por isso devemos viver com gratidão.",
    "O maior tesouro que você pode possuir é um coração cheio de amor.",
    "Cada passo dado em direção ao amor é um passo em direção à paz.",
    "O sol brilha mais forte depois da tempestade.",
    "Cada desafio é uma oportunidade para crescer e ser mais forte.",
    "A beleza da vida está nos detalhes que muitas vezes passam despercebidos.",
    "O verdadeiro poder está em amar sem medo.",
    "A vida é feita de encontros e despedidas, mas o amor é eterno.",
    "O verdadeiro valor de uma pessoa é medido pela bondade de seu coração.",
    "Cada dificuldade enfrentada é um degrau a mais na escada da vida.",
    "Às vezes, é preciso perder-se para encontrar o verdadeiro caminho.",
    "A vida é uma jornada de autodescoberta.",
    "A verdadeira paz vem da aceitação de quem somos.",
    "Os momentos difíceis são apenas capítulos temporários da nossa história.",
    "O que você dá ao mundo é o que o mundo dá a você.",
    "O amor é o que torna a vida mais rica e significativa.",
    "A verdadeira beleza é a de um coração que vive em harmonia com o mundo."
];


var b = document.getElementById("p1")
$(".button").click(function() {
    b.textContent = (embname(frases)[0]);
});